### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by awptechnologies** [shizunge/dockerhub-mirror#8]
So im using your repo to try and make my own mirror like you mentioned on my issue on sheperd. 

What are variables and what are secrets? 

I use gitea and self host my own git server and i have runners that can do the github actions. Im trying to set the variables and secrets so i dont exspose anything.

matrix.image 
tokens 
users

can you help me out?

**Comment by shizunge** [comment]
The workflow uses
```
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
```
So it only support github registry.
You need to change those lines for other registry.

**Comment by awptechnologies** [comment]
what about matrix image? and are you setting those as secrets or variables. In gitea i can set those in my profile.

**Comment by shizunge** [comment]
This repo depends on github workflow. You want to read Github document about the their workflow to learn more like matrix image. Github sets these variables automatically. I don't know if gitea supports github workflow, or what CI/CD is used by gitea.

**Comment by shizunge** [comment]
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow

**Comment by awptechnologies** [comment]
https://gitea.awptechnologies.co/awptechnologies/Docker-Mirror

check this out for me see what you think!

**Comment by shizunge** [comment]
Sorry I don't have time for this.

**Comment by shizunge** [comment]
If you're concerned about Docker Hub rate limits, you might consider trying my build: https://github.com/shizunge/gantry . One reason I built Gantry was to offer an alternative with potentially lower Docker Hub usage.
